import { L } from '../levels.js';
import { ja, jaEllerUkendt, tal } from '../helpers.js';

export const feberVoksen = {
  id: 'feber_voksen',
  titel: 'Feber (voksen)',
  gruppe: 'Infektion og feber',
  soegeord: ['feber', 'temperatur', 'sepsis', 'kulderystelser', 'influenza'],
  gaelderFor: (p) => p.alderAar === undefined || p.alderAar >= 16,
  gaelderForTekst: '16 år og derover',
  spoergsmaal: [
    { id: 'temp', tekst: 'Højeste målte temperatur', type: 'tal', enhed: '°C', min: 34, max: 43, valgfri: true },
    { id: 'dage', tekst: 'Hvor mange dage har patienten haft feber?', type: 'tal', enhed: 'dage', min: 0, max: 365 },
    { id: 'nakkestiv', tekst: 'Nakkestivhed (kan ikke bøje hagen ned mod brystet) eller kraftig hovedpine?', type: 'janej' },
    { id: 'forvirret', tekst: 'Er patienten ny-opstået forvirret eller usædvanligt døsig?', type: 'janej' },
    { id: 'hurtig_vejrtr', tekst: 'Hurtig vejrtrækning eller åndenød?', type: 'janej' },
    { id: 'lav_urin', tekst: 'Ingen eller meget lidt vandladning de seneste 12 timer?', type: 'janej' },
    { id: 'kulderystelser', tekst: 'Kraftige kulderystelser?', type: 'janej' },
    { id: 'flankesmerter', tekst: 'Smerter i flanken/lænden eller svie ved vandladning?', type: 'janej' },
    { id: 'udland', tekst: 'Rejst i tropiske/subtropiske områder (fx malariaområde) inden for 3 måneder?', type: 'janej' },
    { id: 'operation', tekst: 'Opereret eller udskrevet fra hospital inden for 2 uger?', type: 'janej' },
  ],
  regler: [
    { niveau: L.AKUT, hvis: (a) => jaEllerUkendt(a, 'forvirret'), tekst: 'Feber med bevidsthedspåvirkning – mulig sepsis' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'hurtig_vejrtr'), tekst: 'Feber med hurtig vejrtrækning – mulig sepsis/lungebetændelse' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'lav_urin'), tekst: 'Feber med nedsat urinproduktion – mulig sepsis' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'nakkestiv'), tekst: 'Feber med nakkestivhed/kraftig hovedpine – mulig meningitis' },
    {
      niveau: L.AKUT,
      hvis: (a, p) => (p.har('kemoterapi') || p.har('immunsupprimeret')) && (tal(a, 'temp') ?? 38) >= 38,
      tekst: 'Feber hos immunsupprimeret/i kemoterapi – mulig neutropen feber',
      rute: 'onkologi',
    },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'udland'), tekst: 'Feber efter ophold i troperne – malaria skal udelukkes samme dag' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'operation'), tekst: 'Feber efter nylig operation/indlæggelse' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'kulderystelser'), tekst: 'Feber med kulderystelser' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'flankesmerter'), tekst: 'Feber med flankesmerter – mulig nyrebækkenbetændelse' },
    { niveau: L.SAMME_DAG, hvis: (a) => (tal(a, 'temp') ?? 0) >= 40, tekst: 'Temperatur 40 °C eller derover' },
    { niveau: L.SAMME_DAG, hvis: (a) => (tal(a, 'dage') ?? 0) >= 5, tekst: 'Feber i 5 dage eller mere' },
    { niveau: L.FAA_DAGE, hvis: (a) => (tal(a, 'dage') ?? 0) >= 3, tekst: 'Feber i 3 dage eller mere uden kendt årsag' },
  ],
  standard: () => ({ niveau: L.EGENOMSORG, tekst: 'Kortvarig feber uden alarmsymptomer' }),
  raad: [
    'Drik rigeligt og hvil. Febernedsættende (fx paracetamol) kan bruges efter indlægssedlen ved ubehag.',
    'Mål temperaturen 2-3 gange dagligt.',
  ],
  sikkerhedsnet: [
    'Kontakt igen ved forvirring, hurtig vejrtrækning, ingen vandladning, prikket udslæt, eller hvis patienten bliver dårligere.',
    'Kontakt lægen hvis feberen varer mere end 3 dage.',
  ],
};

export const feberBarn = {
  id: 'feber_barn',
  titel: 'Feber (barn)',
  gruppe: 'Infektion og feber',
  soegeord: ['feber', 'barn', 'spædbarn', 'baby', 'temperatur', 'feberkramper'],
  gaelderFor: (p) => p.alderAar === undefined || p.alderAar < 16,
  gaelderForTekst: 'Under 16 år',
  spoergsmaal: [
    { id: 'temp', tekst: 'Højeste målte temperatur (rektalt)', type: 'tal', enhed: '°C', min: 34, max: 43, valgfri: true },
    { id: 'dage', tekst: 'Hvor mange dage har barnet haft feber?', type: 'tal', enhed: 'dage', min: 0, max: 60 },
    { id: 'slap', tekst: 'Er barnet slapt, svært at vække eller holde vågen, eller "ikke til stede"?', type: 'janej' },
    { id: 'graad', tekst: 'Klynkende, svag eller usædvanlig skinger gråd, eller barnet kan ikke trøstes?', type: 'janej' },
    { id: 'hudfarve', tekst: 'Er huden bleg, grålig, marmoreret eller blålig?', type: 'janej' },
    { id: 'vejrtr', tekst: 'Besværet eller hurtig vejrtrækning, stønnen eller indtrækninger?', type: 'janej' },
    { id: 'nakkestiv', tekst: 'Nakkestivhed eller (under 1½ år) udbulende fontanel?', type: 'janej' },
    { id: 'kramper', tekst: 'Har barnet haft kramper i dette sygdomsforløb?', type: 'janej' },
    { id: 'drikker', tekst: 'Drikker barnet mindre end halvdelen af det normale?', type: 'janej' },
    { id: 'toerre_bleer', tekst: 'Tørre bleer / ingen vandladning i mere end 8 timer?', type: 'janej' },
    { id: 'opkast', tekst: 'Gentagne opkastninger?', type: 'janej' },
    { id: 'oere_hals', tekst: 'Klager barnet over ørepine eller ondt i halsen?', type: 'janej' },
  ],
  regler: [
    { niveau: L.LIVSTRUENDE, hvis: (a) => ja(a, 'slap'), tekst: 'Slapt/svært vækbart barn med feber' },
    { niveau: L.AKUT, hvis: (a) => a.slap === 'ved_ikke', tekst: 'Barnets vågenhed kan ikke vurderes sikkert' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'hudfarve'), tekst: 'Bleg/marmoreret/blålig hud' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'vejrtr'), tekst: 'Vejrtrækningspåvirkning' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'nakkestiv'), tekst: 'Nakkestivhed/udbulende fontanel – mulig meningitis' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'graad'), tekst: 'Unormal gråd/utrøstelighed' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'toerre_bleer'), tekst: 'Tegn på væskemangel (tørre bleer)' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'kramper'), tekst: 'Kramper i forbindelse med feber' },
    { niveau: L.AKUT, hvis: (a, p) => p.erSpaed, tekst: 'Feber hos spædbarn under 3 måneder' },
    { niveau: L.SAMME_DAG, hvis: (a, p) => (p.alderMdr ?? 99) < 6 && (tal(a, 'temp') ?? 39) >= 39, tekst: 'Feber ≥ 39 °C hos barn under 6 måneder' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'drikker'), tekst: 'Nedsat væskeindtag' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'opkast'), tekst: 'Feber med gentagne opkastninger' },
    { niveau: L.SAMME_DAG, hvis: (a) => (tal(a, 'dage') ?? 0) >= 3, tekst: 'Feber i 3 dage eller mere' },
    { niveau: L.FAA_DAGE, hvis: (a) => ja(a, 'oere_hals'), tekst: 'Mulig øre-/halsbetændelse' },
  ],
  standard: () => ({ niveau: L.EGENOMSORG, tekst: 'Barn med feber uden alarmsymptomer' }),
  raad: [
    'Giv barnet rigeligt at drikke, gerne lidt ad gangen og ofte.',
    'Let påklædning. Febernedsættende (paracetamol) kan gives efter vægt jf. indlægssedlen, hvis barnet er utilpas.',
    'Hold øje med barnet – også om natten.',
  ],
  sikkerhedsnet: [
    'Kontakt straks læge/vagt hvis barnet bliver slapt, svært at vække, får vejrtrækningsbesvær, prikket udslæt, tørre bleer eller ikke vil drikke.',
    'Kontakt lægen hvis feberen varer mere end 3 dage.',
  ],
};

export const luftveje = {
  id: 'luftveje',
  titel: 'Hoste / forkølelse',
  gruppe: 'Infektion og feber',
  soegeord: ['hoste', 'forkølelse', 'snue', 'bihule', 'covid', 'influenza', 'bronkitis'],
  spoergsmaal: [
    { id: 'aandenoed', tekst: 'Har patienten åndenød eller hurtig vejrtrækning?', type: 'janej' },
    { id: 'goeende', tekst: 'Gøende hoste med hvæsende lyd ved indånding i hvile (barn)?', type: 'janej', visHvis: (a, p) => p.alderAar === undefined || p.alderAar < 10 },
    { id: 'smerter_vejrtr', tekst: 'Smerter i siden af brystet ved dyb vejrtrækning?', type: 'janej' },
    { id: 'hoeje_feber', tekst: 'Feber over 38,5 °C i mere end 3 dage, eller ny feber efter bedring?', type: 'janej' },
    { id: 'blod', tekst: 'Blod i opspyttet?', type: 'janej' },
    { id: 'kronisk_forvaerring', tekst: 'Forværring af kendt KOL/astma (mere slim, mere åndenød)?', type: 'janej' },
    { id: 'bihuler', tekst: 'Svære ensidige smerter over bihuler/tænder med feber i mere end 7 dage?', type: 'janej' },
    { id: 'uger', tekst: 'Hvor mange uger har hosten varet?', type: 'tal', enhed: 'uger', min: 0, max: 200 },
    { id: 'ryger', tekst: 'Er patienten ryger/tidligere ryger?', type: 'janej', visHvis: (a, p) => (p.alderAar ?? 40) >= 40 },
  ],
  regler: [
    { niveau: L.AKUT, hvis: (a) => ja(a, 'goeende'), tekst: 'Mulig svær falsk strubehoste – hvæsende indånding i hvile' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'aandenoed'), tekst: 'Luftvejsinfektion med åndenød' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'smerter_vejrtr'), tekst: 'Respirationssynkrone smerter – mulig lungebetændelse' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'hoeje_feber'), tekst: 'Vedvarende eller ny feber – mulig bakteriel infektion' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'blod'), tekst: 'Blod i opspyt' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'kronisk_forvaerring'), tekst: 'Eksacerbation af kronisk lungesygdom' },
    { niveau: L.FAA_DAGE, hvis: (a) => ja(a, 'bihuler'), tekst: 'Mulig bakteriel bihulebetændelse' },
    { niveau: L.FAA_DAGE, hvis: (a) => (tal(a, 'uger') ?? 0) >= 4 && ja(a, 'ryger'), tekst: 'Langvarig hoste hos ryger ≥ 40 år – bør udredes' },
    { niveau: L.PLANLAGT, hvis: (a) => (tal(a, 'uger') ?? 0) >= 4, tekst: 'Hoste i mere end 4 uger' },
  ],
  standard: () => ({ niveau: L.EGENOMSORG, tekst: 'Almindelig luftvejsinfektion uden alarmsymptomer' }),
  raad: [
    'Forkølelse og hoste går oftest over af sig selv inden for 1-3 uger. Antibiotika hjælper ikke mod virus.',
    'Drik rigeligt, hvil, evt. næsespray med saltvand. Hoste kan vare op til 3-4 uger.',
  ],
  sikkerhedsnet: ['Kontakt igen ved åndenød, høj feber i mere end 3 dage, smerter ved vejrtrækning eller forværring.'],
};

export const halsondt = {
  id: 'halsondt',
  titel: 'Ondt i halsen',
  gruppe: 'Infektion og feber',
  soegeord: ['hals', 'halsbetændelse', 'mandler', 'synke', 'streptokok'],
  spoergsmaal: [
    { id: 'savler', tekst: 'Savler patienten, kan ikke synke spyt, eller har vejrtrækningsbesvær?', type: 'janej' },
    { id: 'trismus', tekst: 'Kan ikke åbne munden ordentligt, grødet stemme eller udtalt ensidig hævelse i halsen?', type: 'janej' },
    { id: 'drikke', tekst: 'Kan ikke drikke tilstrækkeligt pga. smerter?', type: 'janej' },
    { id: 'feber', tekst: 'Feber over 38 °C?', type: 'janej' },
    { id: 'ingen_hoste', tekst: 'Mangler der hoste/snue (dvs. ingen forkølelsessymptomer)?', type: 'janej' },
    { id: 'belaegninger', tekst: 'Hvide belægninger på mandlerne?', type: 'janej' },
    { id: 'lymfeknuder', tekst: 'Ømme, hævede lymfeknuder på halsen?', type: 'janej' },
    { id: 'dage', tekst: 'Hvor mange dage har det stået på?', type: 'tal', enhed: 'dage', min: 0, max: 365 },
  ],
  regler: [
    { niveau: L.LIVSTRUENDE, hvis: (a) => ja(a, 'savler'), tekst: 'Mulig epiglottitis/truede luftveje' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'trismus'), tekst: 'Mulig halsbyld (peritonsillær absces)' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'drikke'), tekst: 'Kan ikke drikke tilstrækkeligt' },
    {
      niveau: L.FAA_DAGE,
      hvis: (a) => ['feber', 'ingen_hoste', 'belaegninger', 'lymfeknuder'].filter((k) => ja(a, k)).length >= 3,
      tekst: 'Centor-score ≥ 3 – podning for streptokokker',
    },
    { niveau: L.FAA_DAGE, hvis: (a) => (tal(a, 'dage') ?? 0) >= 7, tekst: 'Halssmerter i mere end en uge' },
  ],
  standard: () => ({ niveau: L.EGENOMSORG, tekst: 'Ondt i halsen – sandsynligvis virusinfektion' }),
  raad: ['Smertestillende efter indlægssedlen, kolde/lune drikke, halspastiller. Halsbetændelse skyldes oftest virus.'],
  sikkerhedsnet: ['Ring 112 ved savlen eller vejrtrækningsbesvær. Kontakt igen hvis patienten ikke kan åbne munden eller drikke.'],
};

export const oerepine = {
  id: 'oerepine',
  titel: 'Ørepine / ører',
  gruppe: 'Infektion og feber',
  soegeord: ['øre', 'ørebetændelse', 'hørelse', 'flåd'],
  spoergsmaal: [
    { id: 'bag_oeret', tekst: 'Hævelse, rødme eller ømhed bag øret, eller står øret ud fra hovedet?', type: 'janej' },
    { id: 'ansigtslammelse', tekst: 'Skæv mund/lammelse af ansigtet på samme side?', type: 'janej' },
    { id: 'hoeretab', tekst: 'Pludseligt opstået hørenedsættelse (ikke forkølelse/ørevoks)?', type: 'janej' },
    { id: 'feber_dage', tekst: 'Feber og ørepine i mere end 3 dage?', type: 'janej' },
    { id: 'flaad', tekst: 'Flåd (væske/pus) fra øret?', type: 'janej' },
  ],
  regler: [
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'bag_oeret'), tekst: 'Mulig mastoiditis' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'ansigtslammelse'), tekst: 'Ansigtslammelse' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'hoeretab'), tekst: 'Akut høretab – skal vurderes inden for 24 timer' },
    { niveau: L.SAMME_DAG, hvis: (a, p) => (p.alderMdr ?? 99) < 6, tekst: 'Ørepine hos barn under 6 måneder' },
    { niveau: L.FAA_DAGE, hvis: (a) => ja(a, 'feber_dage'), tekst: 'Vedvarende ørepine og feber' },
    { niveau: L.FAA_DAGE, hvis: (a) => ja(a, 'flaad'), tekst: 'Flåd fra øret' },
  ],
  standard: () => ({ niveau: L.EGENOMSORG, tekst: 'Ørepine uden alarmsymptomer' }),
  raad: ['Smertestillende efter indlægssedlen. De fleste ørebetændelser går over af sig selv inden for 2-3 dage.'],
  sikkerhedsnet: ['Kontakt lægen hvis smerterne varer mere end 2-3 dage, ved høj feber eller hævelse bag øret.'],
};
