import { L } from '../levels.js';
import { ja } from '../helpers.js';

export const skade = {
  id: 'skade',
  titel: 'Skade / sår / forbrænding',
  gruppe: 'Skader og hud',
  soegeord: ['sår', 'skade', 'fald', 'brud', 'forstuvning', 'forbrænding', 'bid', 'hovedtraume', 'hjernerystelse'],
  spoergsmaal: [
    { id: 'hoved_bevidstloes', tekst: 'Slag mod hovedet med bevidstløshed, gentagne opkast, forvirring eller tiltagende hovedpine?', type: 'janej' },
    { id: 'hoved_ak', tekst: 'Slag mod hovedet hos patient i blodfortyndende behandling?', type: 'janej', visHvis: (a, p) => p.har('antikoagulans') },
    { id: 'hoejenergi', tekst: 'Højenergitraume (trafikulykke, fald fra stor højde) eller skade på nakke/ryg med føleforstyrrelser?', type: 'janej' },
    { id: 'fejlstilling', tekst: 'Fejlstilling, kan ikke støtte på/bruge den skadede legemsdel, eller kraftig hævelse?', type: 'janej' },
    { id: 'gabende', tekst: 'Gabende sår, der skal lukkes (sys/limes), opstået inden for 24 timer?', type: 'janej' },
    { id: 'kredsloeb', tekst: 'Kold, bleg eller følelsesløs hånd/fod/finger efter skaden?', type: 'janej' },
    { id: 'bid', tekst: 'Bid af dyr eller menneske, som har gennembrudt huden?', type: 'janej' },
    { id: 'forbraending', tekst: 'Forbrænding større end patientens håndflade, med blærer i ansigt/hænder/fødder/kønsorganer, eller elektrisk/kemisk forbrænding?', type: 'janej' },
    { id: 'infektion', tekst: 'Tiltagende rødme, varme, pus eller rød stribe fra et sår?', type: 'janej' },
    { id: 'stivkrampe', tekst: 'Forurenet sår (jord/rust) og ingen stivkrampevaccination inden for 10 år?', type: 'janej' },
  ],
  regler: [
    { niveau: L.LIVSTRUENDE, hvis: (a) => ja(a, 'hoejenergi'), tekst: 'Højenergitraume / mulig rygmarvsskade' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'hoved_bevidstloes'), tekst: 'Hovedtraume med alarmsymptomer', rute: 'skadestue' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'hoved_ak'), tekst: 'Hovedtraume i blodfortyndende behandling – CT-skanning', rute: 'skadestue' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'kredsloeb'), tekst: 'Kredsløbspåvirkning distalt for skade', rute: 'skadestue' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'forbraending'), tekst: 'Større eller kompliceret forbrænding', rute: 'skadestue' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'fejlstilling'), tekst: 'Mulig knoglebrud', rute: 'skadestue' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'gabende'), tekst: 'Sår der skal lukkes (helst inden for 6-8 timer)', rute: 'skadestue' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'bid'), tekst: 'Bidsår – infektionsrisiko, vurdering af antibiotika' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'infektion'), tekst: 'Inficeret sår' },
    { niveau: L.FAA_DAGE, hvis: (a) => ja(a, 'stivkrampe'), tekst: 'Behov for stivkrampevaccination' },
  ],
  standard: () => ({ niveau: L.EGENOMSORG, tekst: 'Mindre skade uden alarmsymptomer' }),
  raad: [
    'Mindre sår: skyl med rent vand og dæk med plaster.',
    'Forstuvning: ro, is (pakket ind), kompression og hævet leje de første dage.',
    'Forbrænding: kølig (ikke iskold) vandbehandling i 20 minutter.',
  ],
  sikkerhedsnet: ['Kontakt igen ved tiltagende smerter, rødme, feber eller hvis patienten ikke kan bruge den skadede legemsdel.'],
};

export const hud = {
  id: 'hud',
  titel: 'Udslæt / hud',
  gruppe: 'Skader og hud',
  soegeord: ['udslæt', 'eksem', 'rosen', 'helvedesild', 'flåt', 'borrelia', 'kløe', 'byld'],
  spoergsmaal: [
    { id: 'afskalning', tekst: 'Blærer eller afskalning af huden med sår i mund, øjne eller kønsorganer?', type: 'janej' },
    { id: 'hurtig_spredning', tekst: 'Hurtigt spredende rødme med feber, eller smerter ude af proportion til hvordan det ser ud?', type: 'janej' },
    { id: 'roedme_feber', tekst: 'Rødt, varmt og hævet område (fx på benet) med feber?', type: 'janej' },
    { id: 'stribe', tekst: 'Rød stribe fra et sår op ad arm/ben?', type: 'janej' },
    { id: 'helvedesild', tekst: 'Bælteformede blærer på den ene side af kroppen (helvedesild)?', type: 'janej' },
    { id: 'helvedesild_oeje', tekst: 'Sidder udslættet i panden, omkring øjet eller på næsetippen?', type: 'janej', visHvis: (a) => ja(a, 'helvedesild') },
    { id: 'byld', tekst: 'Byld større end 1-2 cm eller i ansigtet?', type: 'janej' },
    { id: 'flaat_ring', tekst: 'Rød ring/rødme over 5 cm omkring et flåtbid, dage-uger efter biddet?', type: 'janej' },
  ],
  regler: [
    { niveau: L.AKUT, hvis: (a) => ja(a, 'afskalning'), tekst: 'Mulig alvorlig lægemiddelreaktion (Stevens-Johnson/TEN)' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'hurtig_spredning'), tekst: 'Mulig nekrotiserende bløddelsinfektion' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'helvedesild_oeje'), tekst: 'Helvedesild omkring øjet – risiko for øjenkomplikationer' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'roedme_feber'), tekst: 'Mulig rosen (erysipelas)' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'stribe'), tekst: 'Mulig lymfekarbetændelse' },
    { niveau: L.FAA_DAGE, hvis: (a) => ja(a, 'helvedesild'), tekst: 'Helvedesild – antiviral behandling bør startes inden for 72 timer' },
    { niveau: L.FAA_DAGE, hvis: (a) => ja(a, 'byld'), tekst: 'Byld der evt. skal åbnes' },
    { niveau: L.FAA_DAGE, hvis: (a) => ja(a, 'flaat_ring'), tekst: 'Mulig borrelia (erythema migrans)' },
  ],
  standard: () => ({ niveau: L.PLANLAGT, tekst: 'Hudproblem uden alarmsymptomer – evt. e-konsultation med billede' }),
  raad: ['Et billede af udslættet sendt via e-konsultation kan ofte hjælpe lægen med vurderingen.'],
  sikkerhedsnet: ['Ring 112 ved feber og prikket udslæt, der ikke forsvinder ved glastest.'],
};

export const allergi = {
  id: 'allergi',
  titel: 'Allergisk reaktion / insektstik',
  gruppe: 'Skader og hud',
  soegeord: ['allergi', 'nældefeber', 'hveps', 'bi', 'stik', 'anafylaksi', 'hævelse', 'epipen'],
  spoergsmaal: [
    { id: 'adrenalin', tekst: 'Har patienten brugt sin adrenalinpen (EpiPen/Jext)?', type: 'janej' },
    { id: 'vejrtr', tekst: 'Hæshed, vejrtrækningsbesvær, synkebesvær eller hvæsen?', type: 'janej' },
    { id: 'kredsloeb', tekst: 'Svimmelhed, bleghed, besvimelse eller hjertebanken?', type: 'janej' },
    { id: 'haevelse_ansigt', tekst: 'Hævelse af læber, tunge eller ansigt?', type: 'janej' },
    { id: 'udbredt', tekst: 'Udbredt nældefeber over hele kroppen?', type: 'janej' },
    { id: 'mave', tekst: 'Samtidig opkast eller mavesmerter efter stik/fødevare?', type: 'janej' },
    { id: 'tidligere', tekst: 'Tidligere svær allergisk reaktion (anafylaksi)?', type: 'janej' },
  ],
  regler: [
    { niveau: L.LIVSTRUENDE, hvis: (a) => ja(a, 'adrenalin'), tekst: 'Adrenalin givet – skal altid observeres på hospital' },
    { niveau: L.LIVSTRUENDE, hvis: (a) => ja(a, 'vejrtr'), tekst: 'Allergisk reaktion med luftvejssymptomer' },
    { niveau: L.LIVSTRUENDE, hvis: (a) => ja(a, 'kredsloeb'), tekst: 'Allergisk reaktion med kredsløbspåvirkning' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'haevelse_ansigt'), tekst: 'Angioødem i ansigtet' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'udbredt') && (ja(a, 'mave') || ja(a, 'tidligere')), tekst: 'Udbredt reaktion hos patient med risiko for anafylaksi' },
    { niveau: L.FAA_DAGE, hvis: (a) => ja(a, 'udbredt'), tekst: 'Udbredt nældefeber uden almen påvirkning' },
  ],
  standard: () => ({ niveau: L.EGENOMSORG, tekst: 'Lokal reaktion' }),
  raad: ['Lokal reaktion: køling og evt. antihistamin i håndkøb efter indlægssedlen.'],
  sikkerhedsnet: ['Ring 112 ved hævelse i mund/svælg, vejrtrækningsbesvær, svimmelhed eller besvimelse.'],
};

export const oejne = {
  id: 'oejne',
  titel: 'Øjne / syn',
  gruppe: 'Skader og hud',
  soegeord: ['øje', 'syn', 'rødt øje', 'øjenbetændelse', 'fremmedlegeme', 'nethinde'],
  spoergsmaal: [
    { id: 'kemikalie', tekst: 'Kemikalie (fx kalk, afløbsrens, rengøringsmiddel) i øjet?', type: 'janej' },
    { id: 'synstab', tekst: 'Pludseligt synstab eller markant synsnedsættelse?', type: 'janej' },
    { id: 'glaukom', tekst: 'Rødt, meget smertende øje med hovedpine, kvalme eller regnbuefarvede ringe om lys?', type: 'janej' },
    { id: 'penetrerende', tekst: 'Skade med skarp genstand eller noget med høj fart (fx slibning, hammer) ind i øjet?', type: 'janej' },
    { id: 'nethinde', tekst: 'Nye lysglimt, mange nye "fluer" eller en skygge/gardin for synet?', type: 'janej' },
    { id: 'kontaktlinse', tekst: 'Kontaktlinsebruger med rødt, smertende øje?', type: 'janej' },
    { id: 'fremmedlegeme', tekst: 'Fremmedlegeme eller slag mod øjet?', type: 'janej' },
    { id: 'lysskyhed', tekst: 'Smerter og lysskyhed (ikke kun grus-/sandfornemmelse)?', type: 'janej' },
  ],
  regler: [
    { niveau: L.AKUT, hvis: (a) => ja(a, 'kemikalie'), tekst: 'Kemikalieskade på øjet – skyl straks i mindst 15 minutter', rute: 'oejenafdeling' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'synstab'), tekst: 'Akut synstab', rute: 'oejenafdeling' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'glaukom'), tekst: 'Mulig akut snævervinklet grøn stær', rute: 'oejenafdeling' },
    { niveau: L.AKUT, hvis: (a) => ja(a, 'penetrerende'), tekst: 'Mulig perforerende øjenskade', rute: 'oejenafdeling' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'nethinde'), tekst: 'Mulig nethindeløsning', rute: 'oejenafdeling' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'kontaktlinse'), tekst: 'Mulig hornhindebetændelse hos linsebruger' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'fremmedlegeme'), tekst: 'Fremmedlegeme/stumpt traume mod øjet' },
    { niveau: L.SAMME_DAG, hvis: (a) => ja(a, 'lysskyhed'), tekst: 'Smertende øje med lysskyhed – mulig regnbuehindebetændelse' },
  ],
  standard: () => ({ niveau: L.EGENOMSORG, tekst: 'Rødt øje uden alarmsymptomer – sandsynlig øjenkatar' }),
  raad: ['Øjenkatar går oftest over af sig selv på 1-2 uger. Rens øjet med kogt, afkølet vand. God håndhygiejne.'],
  sikkerhedsnet: ['Kontakt samme dag ved smerter, lysskyhed eller nedsat syn.'],
};
